services:
  - type: web
    name: metabase
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: MB_DB_FILE
        value: /app/metabase.db
    ports:
      - port: 3000
